### PR TITLE
Remove isolated files

### PR DESCRIPTION
**Pull request by nikolai-b**
Removing the isolated files before https://github.com/npct/pct-shiny/pull/132 may cause problems on the website.

### CODE REVIEW

**Comment by nikolai-b** [comment]
@Robinlovelace no need to revert it is a pull request on a branch!

**Comment by Robinlovelace** [comment]
Ah OK - that's great and shows it's a good chance for discussion before it goes 'live'. Could you update it to only remove the wrong folder?

**Comment by Robinlovelace** [comment]
You happy to close this PR?

**Comment by Robinlovelace** [comment]
Thanks for deleting. Any progress on this: https://github.com/npct/pct-shiny/issues/238 - could be fairly simple I imagine. Note: it's only regions outside this file that shouldn't be moved into, so it may be fixed already (in [London](http://pct.bike/london/) it doesn't seem to jump into [london-east](http://pct.bike/london-east/) for example)... so it kind of seems fixed:

https://github.com/npct/pct-shiny/issues/238

**Pull request closed without merging**
